### ISSUE TITLE
Zmienne instancyjne encji Game

### ISSUE THREAD

**Issue by jazithedev** [kamilkuz/eloapp#15]
Zmienić wszystkie z `protected` na `private`.

**Comment by Qziem** [comment]
@ktrzos 
Zgadzam się. Niewiem dlaczego zrobiłem to jako protected. Chyba generowałem to jakimś narzędziem i chyba ono tak zrobiło. W każdym razie poprawka jest na tyle prosta że wypchnąłem bezpośrednio na mastera bez PR-a.
