### ISSUE TITLE
Zmienna instancyjna "deleted" z encji User

### ISSUE THREAD

**Issue by jazithedev** [kamilkuz/eloapp#17]
Trzeba zmienić typ tej zmiennej instancyjnej z "integer" na "boolean". Powinna przyjmować tylko wartości `true` lub `false`.

**Comment by Qziem** [comment]
@ktrzos Zmiana na tyle prosta że wypchnąłem odrazu na master. 
Lokalnie jak pociągniesz dane to chyba będziesz musiał wycześcić cache doctrina.
