### ISSUE TITLE
Integracja z EditorConfig

### ISSUE THREAD

**Issue by jazithedev** [kamilkuz/eloapp#20]
Można projekt zintegrować z https://editorconfig.org aby każde IDE od razu łapało jakie ma być stosowane formatowanie w plikach.

Np. do PHP:
https://github.com/pfefferle/.editorconfigs/blob/master/php-psr-2/.editorconfig

Co o tym myślisz?

**Comment by Qziem** [comment]
@ktrzos 
Czemu nie, można by spróbować ale nie wiem czy to będzie potrafiło uwspólnić format reasona, bo to te wtyczki chyba zarządzają tym jak to się formatuje.

**Comment by jazithedev** [comment]
Zamknę tego kejsa. Nie ma sensu wdrażać tej integracji, skoro będę chciał wdrożyć CI mające zadanie m.in. sprawdzania poprawności kodu PHP.
