### ISSUE TITLE
Przenieść hasło do Bazy danych

### ISSUE THREAD

**Issue by Qziem** [kamilkuz/eloapp#36]
Obecnie hasło jest zaszyfrowane w kodzie aplikacji. Trzebaby je przenieść do bazki. Można zrobić jakąś jedną tabelkę z jedną kolumną  i jednym polem :D . Ewentualenie jeśli zrobimy możliwość logowania na każdego usera to wtedy się ją zaora

**Comment by jazithedev** [comment]
Good idea! :)

**Comment by Qziem** [comment]
zrobione
