### ISSUE TITLE
Wykres statysktyk dla kilku playerów

### ISSUE THREAD

**Issue by Qziem** [kamilkuz/eloapp#45]
Pomysł jest taki:
1. Robimy nowy place i dorabiamy linka w menu: Statistics (albo chars, czy coś takiego)
2. W tym place'ie wyświetlamy wykres, gdzie na osi X (ważne) będzie podziałka czasowa (w sensie dat czyli np: 1 luty, 2 luty itp.). Na osi Y oczywiście punkty
3. Na tym wykresie musi być możliwość malowania wykresów punktów wielu graczy.
4. Można zrobić tak, że np. pod wykresem będą wszyscy graczy i przy nich checkboxy, jak któregoś zaznaczamy to na wykresie maluje się jego linia. 
5. Kwestia jak domyślnie (po wejściu w ten nowy place) ma się malować. Jak dla mnie może być pusty wykres.

**Comment by jazithedev** [comment]
No właśnie coś takiego chciałem zrobić :). Postaram się do tego przysiąść jakoś w przeciągu najbliższych 7-9 dni. Co do domyślnego wyświetlania, to proponuję jakieś TOP pierwszych graczy. Może z 5 - 10.
Co do nazwy, to jak najbardziej "Statistics". Można będzie tam wtedy dodawać jakieś inne statystyki.

**Comment by jazithedev** [comment]
Możesz mnie tu przypisać do tego kejsa ;).

**Comment by Qziem** [comment]
Kurde, właśnie ja tez nie mogę. W tych podpowiedziach tylko ja widnieje. Chyba musisz być kolaborantem - dodałem Cię, chyba powinieneś dostać jakieś zaproszenie.

**Comment by jazithedev** [comment]
To jest już dawno zrobione, więc zamykam :).
