### ISSUE TITLE
Kanban w projekcie

### ISSUE THREAD

**Issue by ZielonyBuszmen** [kamilkuz/eloapp#49]
Co myślicie, by wykorzystać githubowe dobrodziejstwa, i założyć kanbana? Wówczas widać by było jak na dłoni, kto co robi i w jakim stadium jest dany case?

Mówię o zakładce "Projects", podczas zakładania można wybrać np. "automated kanban" i go skonfigurować pod swoje potrzeby

**Comment by Qziem** [comment]
Myśle że spoko pomysł. Będzie przydatny jeśli będziemy rzeczywiście rozwijać eloappa :P
Mogę spróbować to ogarnąć w wolnej chwili

**Comment by jazithedev** [comment]
Mi się wydaje, że przy takiej skali projektu, i przy robionych 1-3 zadaniach na miesiąc, na razie aż tak potrzebne to nie jest ;). Ale zawsze coś nowego do zrobienia :P.

**Comment by ZielonyBuszmen** [comment]
@ktrzos Miło dla oka będzie, a projekt będzie wydawał się bardziej profesjonalny ;)

**Comment by jazithedev** [comment]
Według mnie można zamknąć tego kejsa. Uważam, że jest wszystko uwidocznione w dziale **Issues.** Jeśli ktoś zajmuje się danym kejsem, to jest do niego przypisany. Jeśli jest w CR, to jest do niego utworzony PR. Zamykaniem proponuję, aby zajmował się Qzmen, gdyż i on będzie wdrażał kod na produkcję (póki nie mamy żadnego automatu). Nie ma co sobie komplikować życia :). Tym bardziej, że tak dużo zgłoszeń też nie mamy, aby nie ogarniać :).

**Comment by Qziem** [comment]
Chciałem to ogarnąć, ale w sumie mi się nie chce :P i generalnie zgadam się z tym co napisał Krzysztof T.
