### ISSUE TITLE
Błąd gdy w inpucie wpiszwmy slash

### ISSUE THREAD

**Issue by Qziem** [kamilkuz/eloapp#54]
Np. przy pobieraniu statystyk, gdy wpiszemy: cośtam/ to wywala się błąd 404 bo przez slasha myśli że to path. Trzeba odpowiednio kodować wszystkie stringi które są wysyłane getem.

**Comment by jazithedev** [comment]
Tak swoją drogą, to w przypadku wysyłania danych na serwer, takie formularze powinny przesyłać dane poprzez POST. Chyba prawilnie, zamiast kodować stringi, powinniśmy przenieść typ requestu z GET na POST. Postaram się do tematu przysiąść w środę.

**Comment by Qziem** [comment]
Ale czy to nie jest sprzeczne z założeniami resta ? W przypadku pobierania statystyk nic nie jest modyfikowane ani wstawiane do bazy, z tego co czytałem o REST to wtedy powinno się wykonywać geta.
Zresztą chyba sam o tym pisałeś w którymś z pr-ów

**Comment by jazithedev** [comment]
Zamuliłem. Masz rację.

**Comment by jazithedev** [comment]
Stworzyłem PR naprawiającego tego buga: #61.

**Comment by Qziem** [comment]
domergowane i wgrane na produkcje
